apiVersion: v1
kind: ConfigMap
metadata:
  name: arnold-products-config
  namespace: arnold-products
data:
  # RONDA 5: Configuración de servicios externos
  MONGODB_URI: "mongodb://admin:admin123@mongodb:27017/arnold_products"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Spring Boot
  SPRING_PROFILES_ACTIVE: "kubernetes"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_EMPRESA: "DEBUG"
